import { ApiError } from './errors.js';
export type Json=Record<string,unknown>;
export interface ClientOptions { baseUrl:string; token:string; timeoutMs?:number; fetchImpl?:typeof fetch; }
export class BridgeClient {
 private readonly fetcher:typeof fetch; constructor(private readonly options:ClientOptions){this.fetcher=options.fetchImpl??fetch;}
 public async request<T=Json>(method:string,path:string,body?:unknown,headers:Record<string,string>={}):Promise<T>{const controller=new AbortController();const t=setTimeout(()=>controller.abort(),this.options.timeoutMs??30000);try{const r=await this.fetcher(this.options.baseUrl.replace(/\/$/,'')+path,{method,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${this.options.token}`,'User-Agent':'modx-ai-bridge-sdk-ts/0.2',...headers},body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal});const data=await r.json().catch(()=>({}));if(!r.ok){const e=(data as any).error??{};throw new ApiError(e.message??'API request failed',r.status,e.code,e.details??{});}return data as T;}finally{clearTimeout(t);}}
 capabilities(){return this.request('GET','/api/ai/v2/capabilities');} profiles(){return this.request('GET','/api/ai/v2/profiles');}
 siteSchema(params:Record<string,string|number>={}){const q=new URLSearchParams(Object.entries(params).map(([k,v])=>[k,String(v)]));return this.request('GET','/api/ai/v2/site/schema'+(q.toString()?`?${q}`:''));}
 siteFingerprint(){return this.request('GET','/api/ai/v2/site/fingerprint');} contentContract(templateId?:number){return this.request('GET','/api/ai/v2/content/contract'+(templateId===undefined?'':`?template_id=${templateId}`));}
 validateContent(content:Json,contract:Json){return this.request('POST','/api/ai/v2/content/validate',{content,contract});}
 createResource(resource:Json,idempotencyKey:string=crypto.randomUUID()){return this.request('POST','/api/ai/v2/resources',resource,{'Idempotency-Key':idempotencyKey});}
 getResource(id:number){return this.request('GET',`/api/ai/v2/resources/${id}`);}
 updateResource(id:number,resource:Json,idempotencyKey:string=crypto.randomUUID()){return this.request('PATCH',`/api/ai/v2/resources/${id}`,{...resource,id}, {'Idempotency-Key':idempotencyKey});}
 deleteResource(id:number,idempotencyKey:string=crypto.randomUUID()){return this.request('DELETE',`/api/ai/v2/resources/${id}`,undefined,{'Idempotency-Key':idempotencyKey});}
 previewResource(resource:Json){return this.request('POST','/api/ai/v2/resources/preview',resource);}
 publishResource(id:number,approvalId:string,idempotencyKey:string=crypto.randomUUID()){return this.request('POST',`/api/ai/v2/resources/${id}/publish`,{approval_id:approvalId},{'Idempotency-Key':idempotencyKey});}
 job(id:string){return this.request('GET',`/api/ai/v2/jobs/${id}`);}
 async waitForJob(id:string,timeoutMs=60000,pollMs=1000){const end=Date.now()+timeoutMs;while(Date.now()<end){const j:any=await this.job(id);const s=j.data?.status??j.job?.status??j.status;if(['completed','failed','cancelled'].includes(s))return j;await new Promise(r=>setTimeout(r,pollMs));}throw new ApiError('Job polling timeout',408,'job_timeout',{job_id:id});}
}
export class McpClient { private id=0; constructor(private readonly bridge:BridgeClient){} initialize(clientInfo={name:'modx-ai-bridge-sdk-ts',version:'0.2.0'}){return this.bridge.request('POST','/api/ai/v2/mcp',{jsonrpc:'2.0',id:++this.id,method:'initialize',params:{clientInfo}});} tools(){return this.call('tools/list');} callTool(name:string,arguments_:Json={}){return this.call('tools/call',{name,arguments:arguments_});} resources(){return this.call('resources/list');} readResource(uri:string){return this.call('resources/read',{uri});} prompts(){return this.call('prompts/list');} getPrompt(name:string,arguments_:Json={}){return this.call('prompts/get',{name,arguments:arguments_});} private call(method:string,params:Json={}){return this.bridge.request('POST','/api/ai/v2/mcp',{jsonrpc:'2.0',id:++this.id,method,params});}}
